"""initial schema

Revision ID: 0ecdcbd5fcbd
Revises: 
Create Date: 2026-08-30 12:51:54.693253
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0ecdcbd5fcbd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Enum('dsa', 'backend', 'frontend', 'aiml', 'cyber', name='topic'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('prompt_md', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=False),
    sa.Column('time_limit_s', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puzzles_topic'), 'puzzles', ['topic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), server_default='1200', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_rating_desc', 'users', [sa.text('rating DESC')], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Enum('dsa', 'backend', 'frontend', 'aiml', 'cyber', name='topic'), nullable=False),
    sa.Column('puzzle_id', sa.UUID(), nullable=False),
    sa.Column('player_a', sa.UUID(), nullable=False),
    sa.Column('player_b', sa.UUID(), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'finished', 'abandoned', name='match_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player_b'], ['users.id'], ),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_player_a'), 'matches', ['player_a'], unique=False)
    op.create_index(op.f('ix_matches_player_b'), 'matches', ['player_b'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('puzzle_testcases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('puzzle_id', sa.UUID(), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=False),
    sa.Column('expected_stdout', sa.Text(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puzzle_testcases_puzzle_id'), 'puzzle_testcases', ['puzzle_id'], unique=False)
    op.create_table('rating_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('old_rating', sa.Integer(), nullable=False),
    sa.Column('new_rating', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_history_user_id'), 'rating_history', ['user_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('tests_passed', sa.Integer(), nullable=False),
    sa.Column('tests_total', sa.Integer(), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_match_id'), 'submissions', ['match_id'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_match_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_rating_history_user_id'), table_name='rating_history')
    op.drop_table('rating_history')
    op.drop_index(op.f('ix_puzzle_testcases_puzzle_id'), table_name='puzzle_testcases')
    op.drop_table('puzzle_testcases')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_player_b'), table_name='matches')
    op.drop_index(op.f('ix_matches_player_a'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_rating_desc', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_puzzles_topic'), table_name='puzzles')
    op.drop_table('puzzles')
    # ### end Alembic commands ###
    sa.Enum(name='match_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='topic').drop(op.get_bind(), checkfirst=True)
